- hosts: localhost
  gather_facts: no
  vars_files:
    - keys.yml
  vars:
    DEFAULT_VPC_SUBNET: subnet-3ecb9f5a 
    BASE_AMI: ami-04d7a5c80d7e582b9
    AWS_ZONE: eu-west-1b
    SECURITY_GROUP: sg-00cacfc118d60aec3
  tasks:

    - name: Create AWS key pair using Ansibles key
      ec2_key:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        security_token: "{{ AWS_SESSION_TOKEN }}"
        ec2_region: "{{ AWS_REGION }}"
        name: ansible_keypair
        key_material: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"

    - name: Provision instance
      ec2:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        security_token: "{{ AWS_SESSION_TOKEN }}"
        ec2_region: "{{ AWS_REGION }}"
        zone: "{{ AWS_ZONE }}"
        instance_type: t2.xlarge
        group_id: "{{ SECURITY_GROUP }}"
        keypair: ansible_keypair
        image: "{{ BASE_AMI }}"
        assign_public_ip: yes
        volumes:
        - device_name: /dev/sda1
          volume_type: gp2
          volume_size: "50"
          delete_on_termination: true
        vpc_subnet_id: "{{ DEFAULT_VPC_SUBNET }}"
        wait: true
        count: 1
        instance_tags:
          Owner: m.kingston@f5.com
          Name: "NGINX MGMT Suite"
      register: ec2
