- hosts: demogroup
  remote_user: admin #user on the ec2 instance
  become: yes
  vars_files:
    - keys.yml
  tasks:

  - name: Login to the controller
    uri:
      url: https://{{ controller.hostname }}/api/{{ controller.api_version }}/platform/login
      method: POST
      body_format: json 
      body: 
        credentials: 
          type: "BASIC"
          username: "{{ controller.admin_email }}"
          password: "{{ controller.admin_password }}"
      status_code: 204
      validate_certs: False
    register: session

  - name: Store session cookie as fact
    set_fact:
      nginx_controller_session: "{{ session }}"

  - name: Upload the controller license
    uri:
      url: https://{{ controller.hostname }}/api/{{ controller.api_version }}/platform/license-file
      method: POST
      headers:
        Cookie: "session={{ nginx_controller_session.cookies.session }}"
      body_format: json
      body:
        content: "{{ lookup( 'file', controller.license_file ) | b64encode }}"
      status_code: 200
      validate_certs: False
