- hosts: localhost
  gather_facts: no
  vars_files:
    - keys.yml
  vars:
    DEFAULT_VPC_SUBNET: subnet-3ecb9f5a
    BASE_AMI: ami-04d7a5c80d7e582b9
    AWS_ZONE: eu-west-1b
    SECURITY_GROUP: sg-00cacfc118d60aec3
  tasks:

    - name: Create AWS key pair using Ansibles key
      ec2_key:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        security_token: "{{ AWS_SESSION_TOKEN }}"
        ec2_region: "{{ AWS_REGION }}"
        name: ansible_keypair
        key_material: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"

    - name: Provision instance
      ec2:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        security_token: "{{ AWS_SESSION_TOKEN }}"
        ec2_region: "{{ AWS_REGION }}"
        zone: "{{ AWS_ZONE }}"
        instance_type: t2.xlarge
        group_id: "{{ SECURITY_GROUP }}"
        keypair: ansible_keypair
        image: "{{ BASE_AMI }}"
        assign_public_ip: yes
        volumes:
        - device_name: /dev/sda1
          volume_type: gp2
          volume_size: "100"
          delete_on_termination: true
        vpc_subnet_id: "{{ DEFAULT_VPC_SUBNET }}"
        wait: true
        count: 1
        instance_tags:
          Owner: m.kingston@f5.com
          Name: "k8s master"
      register: ec2_master


    - name: Provision instance
      ec2:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        security_token: "{{ AWS_SESSION_TOKEN }}"
        ec2_region: "{{ AWS_REGION }}"
        zone: "{{ AWS_ZONE }}"
        instance_type: t2.xlarge
        group_id: "{{ SECURITY_GROUP }}"
        keypair: ansible_keypair
        image: "{{ BASE_AMI }}"
        assign_public_ip: yes
        volumes:
        - device_name: /dev/sda1
          volume_type: gp2
          volume_size: "100"
          delete_on_termination: true
        vpc_subnet_id: "{{ DEFAULT_VPC_SUBNET }}"
        wait: true
        count: 1
        instance_tags:
          Owner: m.kingston@f5.com
          Name: "k8s worker 1"
      register: ec2_worker1


    - name: Provision instance
      ec2:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        security_token: "{{ AWS_SESSION_TOKEN }}"
        ec2_region: "{{ AWS_REGION }}"
        zone: "{{ AWS_ZONE }}"
        instance_type: t2.xlarge
        group_id: "{{ SECURITY_GROUP }}"
        keypair: ansible_keypair
        image: "{{ BASE_AMI }}"
        assign_public_ip: yes
        volumes:
        - device_name: /dev/sda1
          volume_type: gp2
          volume_size: "100"
          delete_on_termination: true
        vpc_subnet_id: "{{ DEFAULT_VPC_SUBNET }}"
        wait: true
        count: 1
        instance_tags:
          Owner: m.kingston@f5.com
          Name: "k8s worker 2"
      register: ec2_worker2

    - name: allocate a new elastic IP and associate it with the master node
      ec2_eip:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        security_token: "{{ AWS_SESSION_TOKEN }}"
        ec2_region: "{{ AWS_REGION }}"
        device_id: "{{ ec2_master.instance_ids[0] }}"


    - name: allocate a new elastic IP and associate it with worker 1
      ec2_eip:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        security_token: "{{ AWS_SESSION_TOKEN }}"
        ec2_region: "{{ AWS_REGION }}"
        device_id: "{{ ec2_worker1.instance_ids[0] }}"


    - name: allocate a new elastic IP and associate it with the worker 2
      ec2_eip:
        aws_access_key: "{{ AWS_ACCESS_KEY_ID }}"
        aws_secret_key: "{{ AWS_SECRET_ACCESS_KEY }}"
        security_token: "{{ AWS_SESSION_TOKEN }}"
        ec2_region: "{{ AWS_REGION }}"
        device_id: "{{ ec2_worker2.instance_ids[0] }}"
